spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web2_fullstack?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: web2_user
    password: 123qwe
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: false
