   server:
     port: 8080   # porta que o servidor vai escutar

   spring:
     application:
       name: web2-fullstack-backend  # nome da aplicação

   management:
     endpoints:
       web:
         exposure:
           include: "*"  # quais endpoints do actuator expor
